# Generated by Django 3.2.13 on 2023-09-15 01:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Carreira',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('titulos', models.CharField(max_length=20)),
                ('ano_criacao', models.DateField()),
                ('idade', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Estats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('podium', models.CharField(choices=[('10', 'Top 10'), ('5', 'Top 5'), ('20', 'Top 20')], max_length=2)),
                ('priority', models.IntegerField()),
                ('category', models.CharField(choices=[('J', 'Estatisticas de jogo'), ('C', 'Estatisticas de carreira')], max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='Premios',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=40)),
                ('quantidade', models.CharField(max_length=10)),
                ('maiorquantidade', models.IntegerField()),
                ('podium', models.CharField(choices=[('5', 'Top 5'), ('10', 'Top 10'), ('50', 'Top 50'), ('1', 'Top 1')], max_length=2)),
            ],
        ),
    ]
